// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWLdnK7grcz_3TfwYq3f0Hi72UTYIaz4',
    appId: '1:325182676027:web:35b010539096ea9d40101e',
    messagingSenderId: '325182676027',
    projectId: 'pwlock-134',
    authDomain: 'pwlock-134.firebaseapp.com',
    databaseURL: 'https://pwlock-134-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pwlock-134.appspot.com',
    measurementId: 'G-0YXB4P1C2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqH8NkY5aZXeq9dD-lENvR5tCzzuFXzHA',
    appId: '1:325182676027:android:0bd3da2dce4fdad940101e',
    messagingSenderId: '325182676027',
    projectId: 'pwlock-134',
    databaseURL: 'https://pwlock-134-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pwlock-134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOStGV9kcRc_ee2czfb5Qimy2Uu9NTS0k',
    appId: '1:325182676027:ios:fec8d32cac76dbd140101e',
    messagingSenderId: '325182676027',
    projectId: 'pwlock-134',
    databaseURL: 'https://pwlock-134-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pwlock-134.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOStGV9kcRc_ee2czfb5Qimy2Uu9NTS0k',
    appId: '1:325182676027:ios:f5dd66462b2df64440101e',
    messagingSenderId: '325182676027',
    projectId: 'pwlock-134',
    databaseURL: 'https://pwlock-134-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pwlock-134.appspot.com',
    iosBundleId: 'com.example.untitled9.RunnerTests',
  );
}
